<div class="controls">
    <?= $this->tabs ?>
    <div style="margin: 1em;" class="dontprint">
        <?= $intervalBox; ?>
    </div>
</div>
<?php foreach ($charts as $type => $chart): ?>

<div class="content alerthistogram">
    <h1><?php printf(
    $this->translate('Alert Histogram for %s'),
    $type
); ?></h1>
</div>

<div class="svg-container-responsive">
    <?= $chart->render() ?>
</div>
<?php endforeach; ?>
